### ISSUE TITLE
makeReport.se:submitReport does not use salt, shaHash can be "ground" to find the best event for reporter

### ISSUE THREAD

**Issue by AlexeyAkhunov** [AugurProject/augur-core#151]
The decision on whether to get the reporter to report on the event is made based on this:
`hash = sha3([msg.sender, event], items = 2)`

If a reporter can influence the event creation in any way, he may do a bit of "Proof Of Work" to determine favourable event so that he does or does not get to report (whatever is the preference). There needs to be something reasonably unpredictable as another argument, so that the decision is more less random

**Comment by joeykrug** [comment]
This "grinding" thing is a fine / a known issue since it's only the 1st of 3 backstops.  If it weren't deterministic and were actually more random this would be a problem, it's designed so that people can precompute the events they need to report on otherwise the UI can't display the events to report on.

Good call on salt though, fixed in a72aae553ae4ab668313739cc362544bb12cec0c [odd, commit message was removed salt from submitReport, now it just says latest, must've happened in the merge from origin]
