### ISSUE TITLE
Run Oyente on All Contracts Pre Bug Bounty Market Launch

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-core#173]
https://github.com/melonproject/oyente

**Comment by joeykrug** [comment]
and http://securify.ch

**Comment by joeykrug** [comment]
We could even add Oyente + Serplint to our CI :)

**Comment by beaugunderson** [comment]
i can handle adding oyente to CI within the next day or two

---

**Comment by joeykrug** [comment]
Sweet
		

		

	





On Thu, Jul 6, 2017 at 5:17 PM -0700, "Beau Gunderson" <notifications@github.com> wrote:










i can handle adding oyente to CI within the next day or two



---

**Comment by beaugunderson** [comment]
opened melonproject/oyente#137 to help with this

**Comment by joeykrug** [comment]
Whatever ended up happening with this

**Comment by joeykrug** [comment]
Also Solidity's SMT checker and Maian

**Comment by nuevoalex** [comment]
Oyente output: https://gist.github.com/nuevoalex/d6c05e546189a4dc90802b179e75478a

**Comment by nuevoalex** [comment]
Most of the detected vulns are for "Transaction Ordering Dependence", which sounds like front running basically. I don't believe these are actual concerns.

The re-entrancy vuln for `MarketFactory.sol:17` I believe is due to the refund of excess provided funds at the end of Market:initialize. This looks fine to me.

The re-entrancy vulns in `Trade.sol`,  `FillOrder.sol`, and `CreateOrder.sol` I believe are actually handled but perhaps not in a way Oyente is not properly detecting. The reentrancy related to assertBalances makes no sense to me. Others should look at these and see if they make sense in a way I'm not seeing though of course.

The re-entrancy vulns in `CompleteSets.sol` don't really make sense to me. We have a gaurd for re-entrancy there like with other trade contracts as well for the case that I believe is legit.

**Comment by tinybike** [comment]
Oyente scripts added in https://github.com/AugurProject/augur-core/pull/588

**Comment by joeykrug** [comment]
Is oyente being run with `-a` so it verifies assertions in the contracts @nuevoalex

**Comment by nuevoalex** [comment]
Nope, didn't even notice that had to be specified. Will add and run to see if we that gets any hits

**Comment by joeykrug** [comment]
Oh sweet

**Comment by nuevoalex** [comment]
Output including assertion checking: https://gist.github.com/nuevoalex/6d1f3552cd2f630e2fa916bc03bf6c9e

Nothing useful or relevant in any of the hits IMO.

**Comment by nuevoalex** [comment]
The first is nonsense I think since that type isn't possible and to arrive at those orderIds isn't something that can be crafted really.

The second is of an error class with oyente's analysis (I think) I saw a few times where it seems to think a variable is a different type than it is.
