### ISSUE TITLE
Use decimal instead of binary fixed-point

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur-core#89]
Using a decimal instead of a binary fixed-point would prevent the small rounding errors that we presently introduce when we convert decimals to their on-contract (int256) representation.  Instead of the base 2^64 representation we use now, my suggestion is to use base 10^19 or base 10^20.

Here's a quick Python example (using base 10^20 and the number 1.2 as an example):
```python
#!/usr/bin/env python
​
from decimal import *
​
base_binary = Decimal(2)**Decimal(64)
base_decimal = Decimal(10)**Decimal(20)
​
def fix_binary(n):
    return Decimal(n) * base_binary
​
def unfix_binary(n):
    return Decimal(n) / base_binary
​
def fix_decimal(n):
    return Decimal(n) * base_decimal
​
def unfix_decimal(n):
    return Decimal(n) / base_decimal
​
n = "1.2"
​
fxp_binary = fix_binary(n)
print "Base 2^64 fixed-point:"
print fxp_binary
print unfix_binary(int(fxp_binary))
​
fxp_decimal = fix_decimal(n)
print "Base 10^20 fixed-point:"
print fxp_decimal
print unfix_decimal(int(fxp_decimal))
```
This outputs:
```
Base 2^64 fixed-point:
22136092888451461939.2
1.199999999999999999989157978
Base 10^20 fixed-point:
120000000000000000000.0
1.2
```
The advantage of the base 10^20 representation is that it avoids the small rounding error introduced by converting to base 2^64.  Also, since Serpent (as far as I know) does not support bitshift operations, the efficiency of binary and decimal fixed-point should be the same.

**Comment by joeykrug** [comment]
If you know how to rewrite the fxp functions [and keep them as accurate] I think that sounds fine [i have no idea tbh].  Although 0.000000000000000000011 imprecision is something i'm willing to live with [more precise than wei + bitcoin anyway].

**Comment by ChrisCalderon** [comment]
You don't need to know how to rewrite the fixed-point functions for a new base. The code being used right now is generated by [a script I wrote](https://github.com/ChrisCalderon/augur-core/blob/forking/tests/fixedpoint_tests/optimal_interp.py) which generates interpolations, tests them with graphs, and spits out tons of serpent code. You just have to tweak my script a bit.

Also, if you round to 10 decimal places instead of 27 or whatever the default is for Decimals, the result should be the same in either case.

**Comment by ChrisCalderon** [comment]
You could even write a script that edits my script, replace all instances of "2**64" with "BASE", and then set BASE to whatever you want, or even add an argparse.ArgumentParser so you can choose a base with a command line option so you can test lots of bases.

**Comment by joeykrug** [comment]
What does generate_serpent(15, 21) the 15 and 21 mean here btw?  And that's great :D

**Comment by ChrisCalderon** [comment]
generate_serpent(15, 21) generates fixed-point serpent functions using 15 to 21 interpolation points, and I don't remember exactly why I had it generate all the different codes in a range instead of only the best one.
graph_errors(15, 21) tests the interpolation polynomials and prints out graphs of the errors. It uses fixed-point algos written in serpent though.

**Comment by tinybike** [comment]
I'm trying to run the optimal_interp.py script now.  The `generate_serpent` function seems to work fine.  The `graph_errors` function throws this error:
```
$ python optimal_interp.py
Traceback (most recent call last):
  File "optimal_interp.py", line 320, in <module>
    graph_errors(15, 21)
  File "optimal_interp.py", line 200, in graph_errors
    log_xs = map(gmpy2.mpfr, linspace(log_min, log_max, 10000))
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/function_base.py", line 89, in linspace
    dtype = result_type(start, stop, float(num))
TypeError: data type not understood
```
Any ideas?  I ran the ubuntu-depends.sh script; are there other dependencies that maybe aren't installed by that script?

**Comment by tinybike** [comment]
Switched to base 10^18 fixedpoint in 5e6594c55a7d27360a044d836d7a3461113cefea.
